### PR TITLE
Update Main.py

### PR DESCRIPTION
**Pull request by pravash21**
Added method to convert URL which is not starting with https:// or http:// to it's valid from by adding https:// or http:// before it as validators.url() method in Python validates URL starting with https:// or http:// so if the user does not enter in that format (which is because most users don't write https:// on the browser as the browser handles it automatically) it will automatically convert it in this format. Do merge the PR :)

### CODE REVIEW

**Comment by Biswa24** [comment]
This will be raise an error for website which only supports 'http' protocol

**Comment by pravash21** [comment]
You first learn about URL and if in python . If any entered URL contains http:// it will remain as it by the code so no error for that. Second, in 3rd if I am adding https:// and https://codechef.com and https://www.codechef.com is same.

**Comment by pravash21** [comment]
And I have tested on various test cases, both on the existing app, for checking which url is working on the app. And also tested the change_url method, using test  cases like, 'http://www.codechef.com' 'www.codechef.com' 'http://codechef.com' 'codechef.com' 'https://www.codechef.com'  etc.

**Comment by Biswa24** [comment]
It would be much better if you would learn a bit of English before teaching URL or if to anyone.
first of all, if a user enters only baseurl and website only supports "HTTP" protocol , is your code able to handle this case in multi-if statements. And  second thing I used the word "guess", that might raise error slicing www from the url.

Thank you for going through our codebase, We will fix this & other bugs reported by users in the second version.

**Comment by pravash21** [comment]
If http:// is entered and if website supports only http, it will remain as it is by the code, And yes I got your point by word guess, but it won't cause any problem by slicing as I mentioned the reason earlier. And, don't teach me English, we know who is fluent in English. And I never corrected anyone's English despite being from the ISC board. And stay cool while commenting and always review the code first.

**Pull request closed without merging**
